### ISSUE TITLE
Update (Ideas + TODO)

### ISSUE THREAD

**Issue by sslp** [turtlecoin/mobile-kotlin#10]
# Ideas

### ReceiveAddressActivity → SendCoinActivity

ReceiveAddressActivity has a Button to link to SendCoinActivity, which would prefill Receiver's Address.

### SendCoinActivity Autofill (DONE)

As proposed in the older [issue](https://github.com/turtlecoin/mobile-kotlin/issues/6), have an AutoCompleteTextView instead of a regular EditText. Upon clicking the Address field a dropdown list would appear showing either the "Aliases" or "Alias : Address" or whatever.

What do you guys think about these ideas?

# TODO (newest pull)

- ~~FIX: When pressing back in EditContactActivity, it crashes to DashboardActivity instead of AddressBookFragment~~
- ~~FIX: When adding first contact remove no contacts image!~~
- ~~FIX: Dashboard -> Account -> Receive CRASH~~

- ADD: Contact book backup & restore
- ADD: Search/Filter Contact book

**Comment by holmholk** [comment]
I'm thinking that a user can have multiple wallets in their profile. Having a button to ReceiveAddressActivity to link to SendCoinActivity can't determine which wallet a user want to send coins from. We can add a dialog or a layout in SendCoinActivity to let users choose the wallet they want to send from, but it will increase complexity. However, if we only allow one wallet per profile (and a user can obtain multiple profiles on one device) then it won't be the problem. Having multiple wallets is pretty useful though, like you can check all of your wallets easily; you can also see the total balance of all the wallets.

I like the idea of autofill. It will make sending coins to multiple registered addresses a lot easier. I think we wouldn't need to link ViewContact(ReceiveAddressActivity) to SendCoinActivity if we have this feature.
