### ISSUE TITLE
Idea: Contact Book

### ISSUE THREAD

**Issue by sslp** [turtlecoin/mobile-kotlin#6]
Hey guys,

How do you find the idea to be able to store people/nicknames with addresses in a contact book?

This is a concept in my old app:

![screener_1516819484305](https://user-images.githubusercontent.com/25178102/35350773-43568f52-013f-11e8-8fe8-8261281b521b.png)

It is relatively simple to implement with an AutoCompleteTextView, which enables a dropdown menu.

I think the dropdown should only be opened once you start typing one's nickname.

Thanks for reading, I appreciate any feedback.

**Comment by neverdot** [comment]
Ya I totally think a contact book would be a nice addition. If we wanted to get super fancy (in the far FAR future) we could even add reacquiring payments, invoices, etc. 

For now a basic contact list would be cool though. Holmholk is kind of in chart of UX so we'll have to see what they think of how/where/when to add it.

**Comment by RocksteadyTC** [comment]
Tell me about reacquiring payments

**Comment by neverdot** [comment]
Typo - meant recurring.

**Comment by sslp** [comment]
Closing issue as everything proposed is implemented
